"""Pure, headless-testable script/loc generators for the wizards.

Each generator takes plain-data snapshots of what the wizard dialogs build
(state from StringVar/Text widgets, captured into dicts at the call site)
and returns the rendered script/loc text. Keeping them out of the closures
in `open_*_wizard(app)` makes them callable from `tests/` without a display
(see `docs/dev/wizards.md` and `docs/dev/testing.md`).

The functions preserve the exact output of the in-closure originals — they
are extracted verbatim, only relocated — so widget-driven callers and
headless callers agree byte-for-byte.
"""

import json

from hoi4cm.focus_tree.loc import LocTarget


def _indent_lines(text, n=1):
    """Indent every non-blank line by n tabs."""
    tab = "\t" * n
    return "\n".join(tab + line if line.strip() else line for line in text.splitlines())


def render_event_txt(ev):
    """Render a single HOI4 event block from an event data object.

    The event object is duck-typed: only attribute reads (not method
    calls), so a plain `types.SimpleNamespace` works in tests.

    Required fields on `ev`:
        etype           e.g. "country_event"
        eid             event id (namespace.number)
        title_text
        desc_text
        picture         gfx key
        major           bool
        fire_once       bool
        triggered       bool
        hidden          bool
        trigger_code    str (raw)
        mtth_days       str (raw, "" when not set)
        mtth_months     str (raw, "" when not set)
        immediate       str (raw)
        options         list of dicts with keys: name, text, effects, ai_chance
    """

    def ind(text, n=2):
        return (
            "\n".join("\t" * n + ln for ln in text.splitlines()) if text.strip() else ""
        )

    out = [f"{ev.etype} = {{"]
    out.append(f"\tid = {ev.eid}")
    out.append(f"\ttitle = {ev.eid}.t")
    out.append(f"\tdesc = {ev.eid}.d")
    out.append(f"\tpicture = {ev.picture}")
    if ev.major:
        out.append("\tmajor = yes")
    if ev.fire_once:
        out.append("\tfire_only_once = yes")
    if ev.triggered:
        out.append("\tis_triggered_only = yes")
    if ev.hidden:
        out.append("\thidden = yes")
    if ev.trigger_code.strip():
        out.append("\ttrigger = {")
        out.append(ind(ev.trigger_code))
        out.append("\t}")
    if ev.mtth_days or ev.mtth_months:
        out.append("\tmean_time_to_happen = {")
        if ev.mtth_days:
            out.append(f"\t\tdays = {ev.mtth_days}")
        if ev.mtth_months:
            out.append(f"\t\tmonths = {ev.mtth_months}")
        out.append("\t}")
    if ev.immediate.strip():
        # Blank line before immediate block (matches MD event file convention).
        out.append("")
        out.append("\timmediate = {")
        # No log injection in immediate — MD convention.
        out.append(ind(ev.immediate))
        out.append("\t}")
    out.append("")
    for opt in ev.options:
        out.append("\toption = {")
        out.append(f"\t\tname = {opt.get('name', 'opt')}")
        opt_effects = opt.get("effects", "").strip()
        opt_name = opt.get("name", "opt")
        # Inject log line only when there are actual effects
        # (MD rule: log only if effects present).
        if opt_effects and "log = " not in opt_effects:
            out.append(
                f'\t\tlog = "[GetDateText]: [This.GetName]: {opt_name} executed"'
            )
        if opt_effects:
            out.append(ind(opt_effects))
        out.append(f"\t\tai_chance = {{ base = {opt.get('ai_chance', '1')} }}")
        out.append("\t}")
    out.append("}")
    return "\n".join(out)


def generate_events_txt(events):
    """Render a multi-event .txt file from a list of event data objects."""
    if not events:
        return ""
    ns_set = list(dict.fromkeys(ev.eid.split(".")[0] for ev in events))
    lines = ["# Generated by HOI4 Content Maker", ""]
    for ns in ns_set:
        lines.append(f"add_namespace = {ns}")
    lines.append("")
    for ev in events:
        lines.append(render_event_txt(ev))
        lines.append("")
    return "\n".join(lines)


def generate_event_loc_yml(events, *, loc_language="english"):
    """Render a localisation YML block for a list of event data objects."""
    if not events:
        return ""
    lines = [LocTarget(loc_language).header(), ""]
    for ev in events:
        lines.append(f" {ev.eid}.t: {json.dumps(ev.title_text, ensure_ascii=False)}")
        lines.append(f" {ev.eid}.d: {json.dumps(ev.desc_text, ensure_ascii=False)}")
        for opt in ev.options:
            opt_text = opt.get("text", opt["name"])
            lines.append(f" {opt['name']}: {json.dumps(opt_text, ensure_ascii=False)}")
        lines.append("")
    return "\n".join(lines)


def build_event_scripted_loc_blocks(event_ids):
    """GET_<id>_title / GET_<id>_desc scripted-loc block pairs, one pair per id.

    `event_ids` is any iterable of event id strings (blank/whitespace-only
    ones are skipped). Blocks are shaped for `hoi4cm.script.append_scripted_loc`
    — mirrors the national spirit wizard's single-id GET_<id>_name pattern,
    generalized to the event wizard's multi-event save.
    """
    blocks = []
    for eid in event_ids:
        eid = (eid or "").strip()
        if not eid:
            continue
        blocks.append({"name": f"GET_{eid}_title", "texts": [], "default": f"{eid}.t"})
        blocks.append({"name": f"GET_{eid}_desc", "texts": [], "default": f"{eid}.d"})
    return blocks


def _strip_val(v):
    if v is None or isinstance(v, bool):
        return ""
    if not isinstance(v, str):
        v = str(v)
    return v.strip()


def generate_decision_block(dec, *, targeted=None, cost_type=None):
    """Render one decision block at the standard 1-tab indent.

    `dec` is a dict (built from the form's StringVars/Text widgets) with
    the keys the wizard populates; the two widget-only knobs are passed
    explicitly so the function stays free of Tk references.

    `targeted`   in {None, "none", "state", "country"}; "none" when None.
    `cost_type`  in {None, "pp", "custom"}; "pp" when None.
    """
    if targeted is None:
        targeted = "none"
    if cost_type is None:
        cost_type = "pp"

    T1 = "\t"
    T2 = "\t\t"
    s = _strip_val
    lines = [f"{T1}{dec['dec_id']} = {{"]

    # allowed
    if s(dec["allowed"]):
        allowed_indented = _indent_lines(s(dec["allowed"]), 3)
        lines.append(f"{T2}allowed = {{\n{allowed_indented}\n{T2}}}")

    # icon (always second, after allowed)
    if s(dec["icon"]):
        icon_val = s(dec["icon"])
        if icon_val and not icon_val.startswith("GFX_"):
            icon_val = f"GFX_decision_{icon_val}"
        lines.append(f"{T2}icon = {icon_val}")

    # targeting
    if targeted != "none":
        if s(dec["target_root_trigger"]):
            trig_indented = _indent_lines(s(dec["target_root_trigger"]), 3)
            lines.append(f"{T2}target_root_trigger = {{\n{trig_indented}\n{T2}}}")
        if s(dec["target_trigger"]):
            trig_indented = _indent_lines(s(dec["target_trigger"]), 3)
            lines.append(f"{T2}target_trigger = {{\n{trig_indented}\n{T2}}}")
        if targeted == "state":
            scope = s(dec.get("state_target_scope", "any"))
            if scope in ("yes", "any", ""):
                lines.append(f"{T2}state_target = yes")
            else:
                lines.append(f"{T2}state_target = {scope}")
            lines.append(
                f"{T2}on_map_mode = {dec.get('on_map_mode', 'map_and_decisions_view')}"
            )
        elif targeted == "country":
            # country targeted: state_target = yes is NOT used
            pass
        if s(dec["targets"]):
            lines.append(f"{T2}targets = {{ {s(dec['targets'])} }}")
        if dec.get("targets_dynamic"):
            lines.append(f"{T2}targets_dynamic = yes")
        if dec.get("target_non_existing"):
            lines.append(f"{T2}target_non_existing = yes")
        if s(dec["target_array"]):
            lines.append(f"{T2}target_array = {s(dec['target_array'])}")
            if targeted == "country" and s(dec.get("on_map_mode", "")):
                lines.append(f"{T2}on_map_mode = {s(dec['on_map_mode'])}")

    if s(dec["visible"]):
        vis_indented = _indent_lines(s(dec["visible"]), 3)
        lines.append(f"{T2}visible = {{\n{vis_indented}\n{T2}}}")
    if s(dec["available"]):
        avail_indented = _indent_lines(s(dec["available"]), 3)
        lines.append(f"{T2}available = {{\n{avail_indented}\n{T2}}}")

    if s(dec.get("highlight_states", "")):
        hs = s(dec["highlight_states"])
        if not hs.startswith("highlight_states"):
            hs_indented = _indent_lines(hs, 3)
            lines.append(f"{T2}highlight_states = {{\n{hs_indented}\n{T2}}}")
        else:
            lines.append(_indent_lines(hs, 2))

    if targeted == "none" and s(dec.get("on_map_mode", "")):
        lines.append(f"{T2}on_map_mode = {s(dec['on_map_mode'])}")

    # mission fields
    if dec.get("is_mission"):
        lines.append(f"{T2}days_mission_timeout = {dec.get('mission_timeout', '100')}")
        if dec.get("selectable_mission"):
            lines.append(f"{T2}selectable_mission = yes")
        if dec.get("is_good"):
            lines.append(f"{T2}is_good = yes")
        if s(dec.get("activation", "")):
            act_indented = _indent_lines(s(dec["activation"]), 3)
            lines.append(f"{T2}activation = {{\n{act_indented}\n{T2}}}")

    if cost_type == "pp":
        if s(dec.get("cost", "")):
            lines.append(f"{T2}cost = {s(dec['cost'])}")
    else:
        if s(dec.get("ai_hint_pp_cost", "")):
            lines.append(f"{T2}ai_hint_pp_cost = {s(dec['ai_hint_pp_cost'])}")
        if s(dec.get("custom_cost_trigger", "")):
            cc_indented = _indent_lines(s(dec["custom_cost_trigger"]), 3)
            lines.append(f"{T2}custom_cost_trigger = {{\n{cc_indented}\n{T2}}}")
        if s(dec.get("custom_cost_text", "")):
            lines.append(f"{T2}custom_cost_text = {s(dec['custom_cost_text'])}")

    if s(dec.get("days_remove", "")):
        lines.append(f"{T2}days_remove = {s(dec['days_remove'])}")
    if s(dec.get("days_re_enable", "")):
        lines.append(f"{T2}days_re_enable = {s(dec['days_re_enable'])}")
    if dec.get("fire_only_once"):
        lines.append(f"{T2}fire_only_once = yes")
    if not dec.get("fixed_random_seed", True):
        lines.append(f"{T2}fixed_random_seed = no")

    # war warnings
    if targeted != "none":
        if dec.get("war_target_complete"):
            lines.append(f"{T2}war_with_target_on_complete = yes")
        if dec.get("war_target_remove"):
            lines.append(f"{T2}war_with_target_on_remove = yes")
    else:
        if s(dec.get("war_complete_tag", "")):
            lines.append(f"{T2}war_with_on_complete = {s(dec['war_complete_tag'])}")
        if s(dec.get("war_remove_tag", "")):
            lines.append(f"{T2}war_with_on_remove = {s(dec['war_remove_tag'])}")

    if s(dec.get("modifier", "")):
        mod_indented = _indent_lines(s(dec["modifier"]), 3)
        lines.append(f"{T2}modifier = {{\n{mod_indented}\n{T2}}}")

    # complete_effect (always emitted when there's an id)
    if s(dec.get("complete_effect", "")):
        ce = s(dec["complete_effect"])
        if "log = " not in ce:
            dec_id = s(dec["dec_id"])
            log_line = f'\t\t\tlog = "[GetDateText]: [Root.GetName]: Decision {dec_id}"'
            ce = log_line + ("\n" + _indent_lines(ce.strip(), 3) if ce.strip() else "")
        else:
            ce = _indent_lines(ce.strip(), 3)
        lines.append(f"{T2}complete_effect = {{\n{ce}\n{T2}}}")
    elif s(dec.get("dec_id", "")):
        dec_id = s(dec["dec_id"])
        lines.append(f"{T2}complete_effect = {{")
        lines.append(f'\t\t\tlog = "[GetDateText]: [Root.GetName]: Decision {dec_id}"')
        lines.append(f"{T2}}}")

    if dec.get("is_mission") and s(dec.get("timeout_effect", "")):
        timeout_indented = _indent_lines(s(dec["timeout_effect"]), 3)
        lines.append(f"{T2}timeout_effect = {{\n{timeout_indented}\n{T2}}}")

    if s(dec.get("remove_effect", "")):
        re_txt = s(dec["remove_effect"])
        if "log = " not in re_txt:
            dec_id = s(dec["dec_id"])
            log_line = f'\t\t\tlog = "[GetDateText]: [Root.GetName]: Decision {dec_id}"'
            re_txt = log_line + (
                "\n" + _indent_lines(re_txt.strip(), 3) if re_txt.strip() else ""
            )
        else:
            re_txt = _indent_lines(re_txt.strip(), 3)
        lines.append(f"{T2}remove_effect = {{\n{re_txt}\n{T2}}}")

    if s(dec.get("cancel_trigger", "")):
        ct_indented = _indent_lines(s(dec["cancel_trigger"]), 3)
        lines.append(f"{T2}cancel_trigger = {{\n{ct_indented}\n{T2}}}")

    if s(dec.get("cancel_effect", "")):
        ce_indented = _indent_lines(s(dec["cancel_effect"]), 3)
        lines.append(f"{T2}cancel_effect = {{\n{ce_indented}\n{T2}}}")

    if dec.get("cancel_if_not_visible"):
        lines.append(f"{T2}cancel_if_not_visible = yes")

    if s(dec.get("remove_trigger", "")):
        rt_indented = _indent_lines(s(dec["remove_trigger"]), 3)
        lines.append(f"{T2}remove_trigger = {{\n{rt_indented}\n{T2}}}")

    # AI
    if s(dec.get("ai_will_do", "")):
        ai_indented = _indent_lines(s(dec["ai_will_do"]), 3)
        lines.append(f"{T2}ai_will_do = {{\n{ai_indented}\n{T2}}}")

    if s(dec.get("priority", "")) not in ("", "1"):
        lines.append(f"{T2}priority = {s(dec['priority'])}")

    lines.append(f"{T1}}}")
    return "\n".join(lines)


def _parse_dyn_mod_line(line):
    """Parse a 'modifier = var = tooltip' modifier line.

    Returns a (modifier, var, tooltip) tuple; empty strings when fields
    are absent. The wizard uses this same shape over lines pasted into a
    Text widget for the dynamic-modifier builder.
    """
    parts = [part.strip() for part in line.split("=", 2)]
    modifier = parts[0] if len(parts) > 0 else ""
    var = parts[1] if len(parts) > 1 else ""
    tooltip = parts[2] if len(parts) > 2 else ""
    return modifier, var, tooltip


def parse_dyn_mod_lines(raw):
    """Parse raw modifier lines into a list of (modifier, var, tooltip).

    Skips blank lines and `#`-comments. Each kept line must have at least
    a modifier key and a variable name.
    """
    entries = []
    for line in raw.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        modifier, var, tooltip = _parse_dyn_mod_line(line)
        if modifier and var:
            entries.append((modifier, var, tooltip))
    return entries


def build_dyn_mod_output(
    *,
    mod_id,
    scope="country",
    icon="",
    enable="",
    mods_raw="",
    const="",
    loc_name="",
    loc_desc="",
    loc_language="english",
):
    """Render the three-file dyn-mod wizard preview (modifier def, focus
    snippet, localisation) in the original wizard's exact format.
    """
    mid = mod_id.strip() or "TAG_my_dynamic_modifier"
    scope = scope.strip()
    icon = icon.strip()
    enable = enable.strip()
    const = const.strip()
    name = loc_name.strip()
    desc = loc_desc.strip()
    loc_target = LocTarget(loc_language)

    mod_entries = parse_dyn_mod_lines(mods_raw)

    dm = [
        "# ============================================================",
        f"# FILE: common/dynamic_modifiers/{mid}.txt",
        "# ============================================================",
        "",
        f"{mid} = {{",
    ]
    if scope != "country":
        dm.append(f"\tscope = {scope}")
    if icon:
        dm.append(f"\ticon = {icon}")
    if enable:
        dm.append("\tenable = {")
        for line in enable.splitlines():
            if line.strip():
                dm.append(f"\t\t{line.strip()}")
        dm.append("\t}")
    dm.append("")
    if mod_entries:
        dm.append("\t# Variable modifiers — read daily from variables")
        for modifier, var, _ in mod_entries:
            dm.append(f"\t{modifier} = {var}")
    if const:
        dm.append("")
        dm.append("\t# Constant modifiers")
        for line in const.splitlines():
            line = line.strip()
            if line and not line.startswith("#"):
                dm.append(f"\t{line}")
    dm.append("}")
    dm.append("")

    dm += [
        "",
        "# ============================================================",
        "# FOCUS SNIPPET — modern add_to_variable pattern",
        "# Use this inside completion_reward = { }",
        "# ============================================================",
        "",
        "\t\tcompletion_reward = {",
        "\t\t\t# Show player which dynamic modifier is being changed",  # noqa: E501
        "\t\t\t# Use adds_dynamic_modifier_tt if this focus also calls add_dynamic_modifier",  # noqa: E501
        "\t\t\t# Use modifies_dynamic_modifier_tt if only changing variables (no add_dynamic_modifier)",  # noqa: E501
        "\t\t\tcustom_effect_tooltip = {",
        "\t\t\t\tlocalization_key = modifies_dynamic_modifier_tt",
        f"\t\t\t\tMODIFIER = {mid}",
        "\t\t\t}",
    ]
    for _modifier, var, tooltip in mod_entries:
        if tooltip:
            dm.append(f"\t\t\tadd_to_variable = {{ {var} = 0.05 tooltip = {tooltip} }}")
        else:
            dm.append(f"\t\t\tadd_to_variable = {{ {var} = 0.05 }}")
    dm += ["\t\t}", ""]

    dm += [
        "",
        "# ============================================================",
        "# LOCALISATION — paste into "
        f"localisation/{loc_target.dirname()}/{loc_target.filename('TAG')}",
        "# File must be UTF-8-BOM encoded",
        "# ============================================================",
        "",
        f" {mid}: {json.dumps(name, ensure_ascii=False)}",
        f" {mid}_desc: {json.dumps(desc, ensure_ascii=False)}",
        ' modifies_dynamic_modifier_tt: "Modifies $MODIFIER$"',
        ' adds_dynamic_modifier_tt: "Adds $MODIFIER$ which grants:"  # for activation focuses',  # noqa: E501
    ]
    if mod_entries:
        dm.append("")
        dm.append(" # Tooltip keys for each modifier stat:")
        for modifier, _var, tooltip in mod_entries:
            if tooltip:
                dm.append(f' {tooltip}: "PLACEHOLDER — describe the {modifier} change"')

    return "\n".join(dm)


def build_national_spirit_output(
    *,
    mod_id,
    name_key="",
    picture="",
    slot="country",
    cost="",
    removal_cost="",
    loc_name="",
    loc_desc="",
    ai_factor="",
    allowed="",
    available="",
    cancel="",
    visible="",
    on_add="",
    on_remove="",
    rule="",
    extra_modifiers="",
    modifiers=None,
    loc_language="english",
):
    """Render the national-spirit (idea) wizard preview output.

    The data shape is what the wizard's form widgets build: scalar IDs
    via StringVar, multi-line blocks via Text widgets. Tests build the
    same dict shape directly.
    """
    sid = (mod_id or "").strip() or "TAG_my_spirit"
    namekey = (name_key or "").strip() or sid
    pic = (picture or "").strip() or f"GFX_idea_{sid}"
    slot = (slot or "").strip() or "country"
    cost = (cost or "").strip()
    removal = (removal_cost or "").strip()
    loc_n = (loc_name or "").strip()
    loc_d = (loc_desc or "").strip()
    ai_f = (ai_factor or "").strip()
    loc_target = LocTarget(loc_language)

    def _block(name, body, indent="\t\t\t"):
        lines = [f"{indent}{name} = {{"]
        for line in body.splitlines():
            if line.strip():
                lines.append(f"{indent}\t{line.strip()}")
        lines.append(f"{indent}}}")
        return lines

    out = []
    out.append("# ============================================================")
    out.append(f"# FILE: common/ideas/{sid}.txt")
    out.append("# ============================================================")
    out.append("")
    out.append("ideas = {")
    out.append(f"\t{slot} = {{")
    out.append(f"\t\t{sid} = {{")
    if namekey != sid:
        out.append(f"\t\t\tname = {namekey}")
    out.append(f"\t\t\tpicture = {pic}")
    if slot == "country":
        out.append("\t\t\tallowed_civil_war = { always = yes }")
    if cost:
        out.append(f"\t\t\tcost = {cost}")
    if removal:
        out.append(f"\t\t\tremoval_cost = {removal}")
    if allowed:
        out += _block("allowed", allowed)
    if available:
        out += _block("available", available)
    if visible:
        out += _block("visible", visible)
    if cancel:
        out += _block("cancel", cancel)
    if on_add:
        out += _block("on_add", on_add)
    if on_remove:
        out += _block("on_remove", on_remove)
    if rule:
        out += _block("rule", rule)

    # Collect modifiers: explicit list first, then any `extra_modifiers`
    # Text-widget content that parses to key=value lines.
    all_mods = list(modifiers) if modifiers else []
    if extra_modifiers:
        for line in extra_modifiers.splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                parts = line.split("=", 1)
                all_mods.append({"key": parts[0].strip(), "value": parts[1].strip()})
    if all_mods:
        valid_mods = []
        for m in all_mods:
            if not isinstance(m, dict):
                continue
            k = m.get("key")
            v = m.get("value")
            if not isinstance(k, str) or not k.strip():
                continue
            if v is None or (isinstance(v, str) and not v.strip()):
                continue
            valid_mods.append((k.strip(), str(v).strip()))
        if valid_mods:
            out.append("\t\t\tmodifier = {")
            for k, v in valid_mods:
                out.append(f"\t\t\t\t{k} = {v}")
            out.append("\t\t\t}")

    if ai_f and ai_f != "0":
        out.append(f"\t\t\tai_will_do = {{ factor = {ai_f} }}")

    out.append("\t\t}")
    out.append("\t}")
    out.append("}")
    out.append("")
    out.append("# ============================================================")
    out.append(
        "# LOCALISATION  "
        f"localisation/{loc_target.dirname()}/{loc_target.filename(sid)}"
    )
    out.append("# ============================================================")
    out.append("")
    out.append(f" {sid}: {json.dumps(loc_n, ensure_ascii=False)}")
    out.append(f" {sid}_desc: {json.dumps(loc_d, ensure_ascii=False)}")
    return "\n".join(out)


def _decs_for_uid(decs, uid):
    """Return the decisions whose cat_uid matches uid (wizard's `_decs_for`)."""
    return [d for d in decs if d["cat_uid"] == uid]


def generate_decision_scripted_loc(cats, decs):
    """Render the scripted_localisation defined_text blocks.

    `cats` and `decs` are the wizard's data dicts; each decision carries a
    `cat_uid` field linking it to a category.
    """
    out = [
        "# ================================================================",
        "# FILE: common/scripted_localisation/TAG_scripted_loc.txt",
        "# ================================================================",
        "# These defined_text blocks let you reference decision/category names",
        "# dynamically in localisation via [GetVariableName]",
        "# ================================================================\n",
    ]
    for cat in cats:
        cid = cat["cat_id"].strip()
        if not cid:
            continue
        out.append("defined_text = {")
        out.append(f"\tname = GET_{cid}_name")
        out.append("\ttext = {")
        out.append(f"\t\tlocalization_key = {cid}")
        out.append("\t}")
        out.append("}\n")
        if cat.get("loc_desc", "").strip():
            out.append("defined_text = {")
            out.append(f"\tname = GET_{cid}_desc")
            out.append("\ttext = {")
            out.append(f"\t\tlocalization_key = {cid}_desc")
            out.append("\t}")
            out.append("}\n")
        for dec in _decs_for_uid(decs, cat["uid"]):
            did = dec["dec_id"].strip()
            if not did:
                continue
            out.append("defined_text = {")
            out.append(f"\tname = GET_{did}_name")
            out.append("\ttext = {")
            out.append(f"\t\tlocalization_key = {did}")
            out.append("\t}")
            out.append("}\n")
            if dec.get("loc_desc", "").strip():
                out.append("defined_text = {")
                out.append(f"\tname = GET_{did}_desc")
                out.append("\ttext = {")
                out.append(f"\t\tlocalization_key = {did}_desc")
                out.append("\t}")
                out.append("}\n")
    return "\n".join(out)


def generate_decision_categories_file(cats, decs):
    """Render the common/decisions/categories/...txt file."""
    T1 = "\t"
    T2 = "\t\t"
    out = [
        "# ================================================================",
        "# FILE: common/decisions/categories/TAG_categories.txt",
        "# ================================================================\n",
    ]
    for cat in cats:
        out.append(f"{cat['cat_id']} = {{")
        if _strip_val(cat["allowed"]):
            allowed_ind = _indent_lines(_strip_val(cat["allowed"]), 2)
            out.append(f"{T1}allowed = {{\n{allowed_ind}\n{T1}}}")
        if _strip_val(cat["visible"]):
            vis_ind = _indent_lines(_strip_val(cat["visible"]), 2)
            out.append(f"{T1}visible = {{\n{vis_ind}\n{T1}}}")
        if _strip_val(cat["icon"]):
            out.append(f"{T1}icon = {_strip_val(cat['icon'])}")
        if _strip_val(cat["picture"]):
            out.append(f"{T1}picture = {_strip_val(cat['picture'])}")
        if _strip_val(cat["priority"]) not in ("", "1"):
            out.append(f"{T1}priority = {_strip_val(cat['priority'])}")
        if cat.get("visible_when_empty"):
            out.append(f"{T1}visible_when_empty = yes")
        if _strip_val(cat.get("scripted_gui", "")):
            out.append(f"{T1}scripted_gui = {_strip_val(cat['scripted_gui'])}")
        if _strip_val(cat.get("highlight_states", "")):
            hs = _strip_val(cat["highlight_states"])
            if not hs.startswith("highlight_states"):
                out.append(f"{T1}highlight_states = {{\n{_indent_lines(hs, 2)}\n{T1}}}")
            else:
                out.append(_indent_lines(hs, 1))
        if cat["on_map_area"]:
            out.append(f"{T1}on_map_area = {{")
            out.append(f"{T2}state = {_strip_val(cat.get('map_state', ''))}")
            out.append(f"{T2}name = {_strip_val(cat.get('map_name', ''))}")
            out.append(f"{T2}zoom = {_strip_val(cat.get('map_zoom', '850'))}")
            if _strip_val(cat.get("map_trigger", "")):
                trig_ind = _indent_lines(_strip_val(cat["map_trigger"]), 3)
                out.append(f"{T2}target_root_trigger = {{\n{trig_ind}\n{T2}}}")
            out.append(f"{T1}}}")
        out.append("}\n")
    return "\n".join(out)


def generate_decisions_file(cats, decs, *, targeted=None, cost_type=None):
    """Render the common/decisions/TAG_decisions.txt file.

    `targeted`/`cost_type` are the wizard's form-level targeting/cost
    modes, forwarded to each decision block (the closure resolves them
    from the Tk StringVars before delegating).
    """
    out = [
        "# ================================================================",
        "# FILE: common/decisions/TAG_decisions.txt",
        "# ================================================================\n",
    ]
    for cat in cats:
        cat_decs = _decs_for_uid(decs, cat["uid"])
        if not cat_decs:
            continue
        out.append(f"{cat['cat_id']} = {{")
        for dec in cat_decs:
            out.append(
                "\n"
                + generate_decision_block(dec, targeted=targeted, cost_type=cost_type)
            )
        out.append("}\n")
    return "\n".join(out)


def generate_decision_loc_yml(cats, decs, *, loc_language="english"):
    """Render a localisation YML block for the decision wizard."""
    lines = [LocTarget(loc_language).header()]
    for cat in cats:
        cid = _strip_val(cat["cat_id"])
        if cid:
            lines.append(f" {cid}: {json.dumps(cat['loc_name'], ensure_ascii=False)}")
            if _strip_val(cat.get("loc_desc", "")):
                cat_desc = _strip_val(cat["loc_desc"])
                lines.append(f" {cid}_desc: {json.dumps(cat_desc, ensure_ascii=False)}")
        for dec in _decs_for_uid(decs, cat["uid"]):
            did = _strip_val(dec["dec_id"])
            if did:
                dec_name = json.dumps(dec["loc_name"], ensure_ascii=False)
                lines.append(f" {did}: {dec_name}")
                if _strip_val(dec.get("loc_desc", "")):
                    dec_desc = _strip_val(dec["loc_desc"])
                    lines.append(
                        f" {did}_desc: {json.dumps(dec_desc, ensure_ascii=False)}"
                    )
    return "\n".join(lines) + "\n"


def build_income_spirit_snippet(
    *,
    idea_id,
    country_tag,
    variable_name,
    tooltip_key,
    spirit_name="",
    spirit_desc="",
):
    """Render the additional-income wizard's "also create a spirit" snippet.

    Returns the raw text to paste into an ideas file, plus a localisation
    hint comment. The wizard clipboard-copies exactly this string.
    """
    return (
        f"\t{idea_id} = {{\n"
        f"\t\tname = {idea_id}\n"
        f"\t\tallowed_civil_war = {{ always = yes }}\n"
        f"\t\tpicture = GFX_idea_{idea_id}\n"
        f"\t\tcancel = {{\n"
        f"\t\t\tNOT = {{ original_tag = {country_tag} }}\n"
        f"\t\t}}\n"
        f"\t\tmodifier = {{\n"
        f"\t\t\tcustom_modifier_tooltip = {tooltip_key}\n"
        f"\t\t}}\n"
        f"\t}}\n"
        f"\n"
        f"\t# Localisation needed:\n"
        f"\t# {idea_id}: {json.dumps(spirit_name, ensure_ascii=False)}\n"
        f"\t# {idea_id}_desc: {json.dumps(spirit_desc, ensure_ascii=False)}\n"
        f'\t# {tooltip_key}: "$$[?{variable_name}|+3] from \u00a7Y${idea_id}$\u00a7!\\n"'  # noqa: E501
    )
