"""Tkinter UI helpers for HOI4 Content Maker."""

from hoi4cm.ui.gfx_browser import (
    open_focus_icon_browser,
    open_gfx_placement_editor,
    open_universal_gfx_browser,
)
from hoi4cm.ui.lifecycle import ApplicationLifecycle
from hoi4cm.ui.menubar import build_menubar
from hoi4cm.ui.settings_dialog import open_settings
from hoi4cm.ui.splash import show_splash
from hoi4cm.ui.tasks import (
    get_executor,
    make_progress,
    progress_modal,
    run_bg,
    shutdown_executor,
)
from hoi4cm.ui.theme import (
    BG_CARD,
    BG_DARK,
    BG_HOVER,
    BG_PANEL,
    BLUE,
    BORDER,
    BORDER_G,
    BOX,
    CANVAS_BG,
    FC_BG,
    FC_BORDER,
    FC_SEL,
    FC_SEL_BD,
    GOLD,
    GOLD_DIM,
    GOLD_LT,
    GREEN,
    ICONS,
    MUTEX_COL,
    ORANGE,
    PREREQ_COL,
    PURPLE,
    RED,
    SEL_BG,
    TEAL,
    TEXT,
    TEXT_DIM,
    XGRID,
    YELLOW,
    YGRID,
)
from hoi4cm.ui.thumbnail_grid import ThumbnailItem, VirtualThumbnailGrid
from hoi4cm.ui.toolbar import build_toolbar_row2
from hoi4cm.ui.widgets import Tooltip, _safe_after, _safe_after_idle

__all__ = [
    "BG_CARD",
    "BG_DARK",
    "BG_HOVER",
    "BG_PANEL",
    "BLUE",
    "BORDER",
    "BORDER_G",
    "BOX",
    "CANVAS_BG",
    "FC_BG",
    "FC_BORDER",
    "FC_SEL",
    "FC_SEL_BD",
    "GOLD",
    "GOLD_DIM",
    "GOLD_LT",
    "GREEN",
    "ICONS",
    "MUTEX_COL",
    "ORANGE",
    "PREREQ_COL",
    "PURPLE",
    "RED",
    "SEL_BG",
    "TEAL",
    "TEXT",
    "TEXT_DIM",
    "ThumbnailItem",
    "Tooltip",
    "VirtualThumbnailGrid",
    "XGRID",
    "YELLOW",
    "YGRID",
    "ApplicationLifecycle",
    "_safe_after",
    "_safe_after_idle",
    "build_menubar",
    "build_toolbar_row2",
    "get_executor",
    "make_progress",
    "open_focus_icon_browser",
    "open_gfx_placement_editor",
    "open_settings",
    "open_universal_gfx_browser",
    "progress_modal",
    "run_bg",
    "show_splash",
    "shutdown_executor",
]
